### ISSUE TITLE
Hovering over a function or variable doesn't include standard information when hovering

### ISSUE THREAD

**Issue by YawLighthouse** [JetBrains/EnhancedUnrealEngineDocumentation#10] opened 2023-09-07 20:10 UTC
Hello when using this plugin it does show documentation as expected but it doesn't seem to show the standard expected information of a function or type information. I would have expected it to just add additional information to what's displayed(or at least using the correct description).

With plugin
![image](https://github.com/JetBrains/EnhancedUnrealEngineDocumentation/assets/9409047/58b9d357-8beb-402b-9d2c-fdcbcb617248)

---

Without plugin
![image](https://github.com/JetBrains/EnhancedUnrealEngineDocumentation/assets/9409047/b112a65f-2e40-48ed-8d6d-7f11f3998ea7)

Problem: The information displayed when hovering is basically nothing and unusable and may need to be updated to operate the same as standard Rider.

**Comment by DecoyRS** [comment] 2023-09-15 08:32
Hey @YawLighthouse 
What's your OS, UE version, and if you're using Git, Perforce or Epic Games version of Engine? I've been working on fixing this plugin for 2023.3 (next release of RIder) and I can't reproduce this behavior on WIndows.

**Comment by YawLighthouse** [comment] 2023-09-15 16:57
@DecoyRS Hello!
- OS: Windows 10 Enterprise
    - Version: 22H2
    - OS Build 19045.3448
    - Experience: Windows Feature Experience Pack 1000.19044.1000.0
- Using GitHub Enterprise
- Unreal Engine 5.1.1, custom work fork of the engine that doesn't do significant changes to the engine just has additional plugins pre-installed in the engine and for being able to release on consoles and such
- Rider 2023.2.1
    - Build: #RD-232.9559.61

Let me know if there is anything else you may need from me.

**Comment by DecoyRS** [comment] 2023-09-15 17:03
*sigh
That's the most regular setup that can be out there.
The thing is - this plugin is only responsible for UE Reflection Specifiers and doesn't affect any other docs in any way, so I'm as puzzled as you're why it's happening :)
I'll try to dig it out the next week

**Comment by DecoyRS** [comment] 2023-10-30 18:09
Whelp, it took a little more than a week >_>
Fixed in the 1.231.1 version of the plugin, check Plugins > Installed > Update

**Closed as completed by DecoyRS** 2023-10-30 18:09 UTC
Labels: bug
